#!/usr/bin/env bash

jsFiles=()
cssFiles=()

while IFS= read -r file; do
  jsFiles+=("$file")
done < <(git diff --cached --name-only --diff-filter=ACMR "src/*.js" "src/*.jsx" "gatsby-*.js")

while IFS= read -r file; do
  cssFiles+=("$file")
done < <(git diff --cached --name-only --diff-filter=ACMR "src/*.css")

if [[ "${#jsFiles[@]}" -ne 0 ]]; then
  echo "${jsFiles[@]}" | xargs ./node_modules/.bin/prettier --write
  echo "${jsFiles[@]}" | xargs git add
  echo "${jsFiles[@]}" | xargs ./node_modules/.bin/eslint
fi

if [[ "${#cssFiles[@]}" -ne 0 ]]; then
  echo "${cssFiles[@]}" | xargs ./node_modules/.bin/stylelint
fi
